= Node.js – [small]#Apprendre par l'exemple • Devenez autonome avec JavaScript, l'écosystème npm, le développement front-end, les applications web et en ligne de commande.#
:author: Thomas Parisot
:homepage: https://oncletom.io/node.js
:toc!:

Bienvenue sur la version Web et gratuite de l'ouvrage *Node.js* à paraître aux link:http://www.eyrolles.com[éditions Eyrolles].

J'ai choisi d'explorer une approche collaborative pour la rédaction de l'ouvrage.
L'épreuve que vous consultez est automatiquement actualisée à chaque _commit_ publié sur le link:https://github.com/oncletom/nodebook[dépôt GitHub du projet].

Je souhaite ainsi offrir l'opportunité à des débutants, confirmés et experts d'apporter leurs contributions librement :

- en *posant des questions* ;
- en *corrigeant* une typo ;
- en demandant des *éclaircissements* ;
- en ajoutant leur *expertise*.

J'apprends en explorant des détails jusque-là inconnus,
au contact d'autres praticiens et en abordant des sujets situés en dehors de ma zone de confort.

Bienvenue, bonne lecture et j'espère bonne(s) contribution(s) !

— Thomas

== Sommaire

- <<foreword/foreword-fr.adoc#,Préface de David Bruant>>
- <<foreword/preamble.adoc#,Avant-propos>>
- *Chapitre 1* : <<chapter-01/index.adoc#,Histoire, écosystème et gouvernance>>
- *Chapitre 2* : <<chapter-02/index.adoc#,Installer, mettre à jour et développer>>
- *Chapitre 3* : <<chapter-03/index.adoc#,Jouer avec JavaScript>>
- *Chapitre 4* : <<chapter-04/index.adoc#,Jouer avec Node.js>>
- *Chapitre 5* : <<chapter-05/index.adoc#,Jouer avec npm>>
- *Chapitre 6* : <<chapter-06/index.adoc#,Déployer notre code>>
- *Chapitre 7* : <<chapter-07/index.adoc#,Faire une application web>>
- *Chapitre 8* : <<chapter-08/index.adoc#,Faire un outil en ligne de commande>>
- *Chapitre 9* : <<chapter-09/index.adoc#,Faire une application front-end>>
- *Annexe A* : <<appendix-a/index.adoc#,Sélection de modules npm>>
