:chapterNumber: 8
:chapterId: chapter-08
:sourceDir: ./examples
:nodeCurrentVersion: v10
:npmCurrentVersion: v6
:sectnums:
:revdate: {docdate}
:imagesdir: {indir}
ifdef::env[]
:imagesdir: .
endif::[]

= Créer un outil en ligne de commande

TBD.

====
.Sommaire
- TBD.
====

[abstract]
--
TBD.
--

include::../docs/tip-versions.adoc[]

////
install global : pour quelqu'un qui n'a pas besoin de l'inclure dans un projet.
Être autonome.
En faire un outil système.
Taper la commande sans avoir à se soucier d'autre chose.

utilisation : le nom c'est le même.
Plus logique.
Plus facile à retenir.
Mais ça peut se changer.

node est adapté au modèle de tâche de courte ou longue durée
modèle plus proche des applications web qu'il n'y parait
////

Le développement d'un outil en ligne de commande est proche de celui
d'une <<../chapter-07/index.adoc#,application web>>
(cf. <<../chapter-07/index.adoc#,chapitre 7>>).
L'équivalent du script qui démarre le serveur web est un script exécutable,
les routes de l'application sont des sous-commandes,
les arguments d'URL (_query string_) sont des options et l'affichage dans
un navigateur web est l'affichage dans un terminal.

////
Et la mémoire ?
Le script utilisera la mémoire disponible, à concurrence des autres applications qui tournent sur la même machine
Sur un Raspberry Pi, y'a moins de mémoire donc on peut atteindre plus rapidement des limites si les fichiers dépassent les capacités (centaine de Mo — vs. plus Go sur des ordinateurs modernes)
////

[[start]]
== Créer un script exécutable

La première étape est de transformer un script Node en un script Node exécutable.
Le système d'exploitation ne percevra plus le script comme un simple fichier texte
mais bel et bien comme un programme au même titre que l'exécutable `npm`.

Nous allons apprendre à faire ce cheminement ensemble, jusqu'à rendre notre
code distribuable sous forme d'un <<../chapter-05/index.adoc#modules,module npm>>
(cf. <<../chapter-05/index.adoc#,chapitre 5>>).

[[script]]
=== Au départ, un simple script Node

Ce dont nous avons besoin pour démarrer, c'est d'un script Node que nous
pouvons appeler depuis notre terminal.
Nous allons placer l'exemple suivant dans le répertoire `bin`
(pour _binary_ en anglais, c'est à dire _exécutable_).
Ça n'a pas d'incidence technique mais c'est une pratique courante au sein
de la communauté Node pour repérer plus facilement les exécutables
sans ambiguité.

[source%interactive,javascript]
.bin/time.js
----
include::{sourceDir}/bin/time.js[]
----
<1> Crée un objet qui représente la <<../chapter-03/index.adoc#date,date>> courante — cf. <<../chapter-03/index.adoc#,chapitre 3>> pour se raffraichir la mémoire au sujet de cette API.

include::../docs/tip-examples.adoc[]

L'exécution du script avec Node retourne la date et l'heure courante — selon
l'horloge de l'ordinateur qui exécute le code.

----
$ node bin/time.js
Il est 13h42.
----


[[permissions]]
=== Modifier les permissions du script

Les systèmes d'exploitation modernes distinguent les fichiers ordinaires
des fichiers exécutables.
L'appel à un fichier exécutable se fait sans avoir à connaître quoique ce soit
d'autre que son emplacement.

Essayons d'exécuter le script précédent pour nous en rendre compte.
Pour se faire, nous allons l'invoquer seulement avec son chemin
— ici, son chemin relatif :

----
$ ./bin/time.js
sh: permission denied: ./bin/time.js
----

Le système refuse de l'exécuter car les permissions du fichier ne sont pas
adéquates.
Comme nous ne les connaissons pas, utilisons la commande `ls` ainsi que
l'option `-l` pour afficher ses informations détaillées :

----
$ ls -l bin/time.js
<i>-rw-r--r--</i> oncletom  staff  175 Jun 14 13:47 bin/time.js
----

Cet affichage détaille les permissions du fichier, l'utilisateur et le groupe
propriétaire, son poids et enfin la date de dernière modification.

[NOTE]
.[RemarquePreTitre]#Déchiffrer# Lire les permissions Unix
====
Les permissions sont cryptiques à lire quand on tombe dessus pour la première fois.

Le premier caractère spécifie le type (fichier, répertoire, lien symbolique) et
ensuite, ce sont des blocs de 3 caractères qui décrivent les permissions de
l'utilisateur propriétaire, du groupe propriétaire et du reste des utilisateurs
du système d'exploitation.

Chaque bloc affiche `r` s'il est lisible, `w` s'il est modifiable et
`x` s'il est exécutable — c'est ce dernier qui nous intéresse.
====

Nous allons rendre le fichier exécutable (`+x`) pour notre utilisateur (`u`)
grâce à la commande `chmod`.
Je préfère utiliser cette notation pour car elle évite des effets de bord :

----
$ chmod u+x bin/time.js
----

L'utilisation renouvelée de la commande `chmod` confirme que la
permission _exécutable_ du fichier a été attribuée à l'utilisateur propriétaire
du fichier :

----
$ ls -l bin/time.js
-rwxr--r-- oncletom  staff  175 Jun 14 13:47 bin/time.js
----

Nous sommes accueillis avec un nouveau message d'erreur lorsque nous
tentons d'exécuter le fichier `bin/time.js` :

----
$ ./bin/time.js
./bin/time.js: line 1: use strict: command not found
./bin/time.js: line 3: syntax error near unexpected token `('
----

La bonne nouvelle c'est que le fichier est exécutable.
Par contre, il semblerait que le système d'exploitation aie du mal
à interpréter le fichier.

[[shebang]]
=== Préciser le contexte d'exécution (_shebang_)

Donner les permissions d'exécution à un fichier ne suffit donc pas.
Nous avons perdu un élément contextuel en supprimant l'appel à `node`
dans l'exécution du script et nous allons voir comment rectifier le tir.

[CAUTION]
.[RemarquePreTitre]#Interopérabilité# Un fonctionnement différent sous Windows
====
Ce mécanisme est n'est pas compris par le système d'exploitation Windows.
Ce dernier utilise une surcouche qui serait trop longue à expliquer dans
cet ouvrage.

Je recommande cependant de conserver le contexte d'exécution sous Windows
car l'exécutable `npm` gère l'interopérabilité pour nous.
Nous verrons comment dans la <<package.json,section suivante>>.
====

Le caractère `#` placé en début de ligne d'un script système signale une ligne
placée en commentaire.
C'est l'équivalent du commentaire `//` en ECMAScript.
Il existe un cas spécial : lorsque le caractère `#` est
suivi par un `!` en tout début de fichier.
Le contenu du commentaire est alors utilisé par le système d'exploitation
pour déterminer quel programme utiliser pour interpréter le script.
C'est ce qu'on appelle _shebang_ (en anglais).

Modifions le script de la section précédente pour ajouter le
_shebang_ en entête :

[source,javascript]
.bin/time-sh.js
----
include::{sourceDir}/bin/time-sh.js[lines=1..5]
...
----

La ligne du _shebang_ crée un nouvel environnement d'exécution avec `env`,
référencé ici par son chemin absolu.
Ce nouvel environnement survit pendant la durée d'exécution du programme
passé en argument, ici `node` :

----
$ ./bin/time-sh.js
Il est 13h42.
----

Le dernier effort à faire pour distribuer ce script exécutable de manière
interopérable est de le lier à un
<<../chapter-05/index.adoc#package.json,module npm>>.

[[package.json]]
=== Faire le lien avec un module npm

Nous avons vu dans le <<../chapter-05/index.adoc#,chapitre 5>>
que Node utilisait la valeur `main` du fichier `package.json` pour déterminer
quel script inclure en faisant `require('<module>')` ou `import <module> from '<module>'`.

Le champ `bin` est une transposition de `main` pour associer un script
exécutable à notre module npm.
Par exemple :

[source,json]
.package.json
----
include::package.json[lines="1..3"]
  ...
}
----

Le moyen le plus simple pour tester l'intégration de l'exécutable
avec notre système d'exploitation est de
l'<<../chapter-05/index.adoc#install.global,installer globalement>>.
L'exécutable `npm` sait aussi installer un module à partir
d'un chemin vers un répertoire contenant un fichier `package.json` :

----
$ npm install --global .
----

Par défaut, l'exécutable est disponible sous le nom du module en question,
déclaré dans le champ `name` du fichier `package.json` :

----
$ nodebook.chapter-08
Il est 13h42.
----

[TIP]
.[RemarquePreTitre]#Pratique# Un autre nom ou plusieurs exécutables
====
Le champ `bin` s'écrit sous forme d'un objet si vous souhaitez utiliser
un autre nom que celui du module npm.
La clé correspond au nom de l'exécutable tel qu'il sera utilisable sur le
système tandis que la valeur contient le chemin d'accès au script exécutable.
Plusieurs exécutables sont alors installés si nous renseignons plusieurs
clés et valeurs.

[source,json,subs="-specialchars"]
.package.json
----
{
  "name": "nodebook.chapter-08",
  "bin": {
    "<i>quelle-heure-est-il</i>": "examples/bin/time-sh.js" // <1>
  }
}
----
<1> L'installation de l'exécutable `examples/bin/time-sh.js` se fera sous le nom `quelle-heure-est-il`.
====


[[interactive]]
== Du script au programme interactif

Nous avons appris à transformer un script Node ordinaire en un script
exécutable et prêt à <<../chapter-05/index.adoc#publish,distribué avec npm>>
(cf. <<../chapter-05/index.adoc#,chapitre 5>>).

Cette section se focalise sur l'enrichissement d'un tel script pour en faire
une application plus complète, interactive et robuste.
De quoi se constituer un outillage sur mesure, partageable avec le reste de
notre équipe et de l'écosystème de modules npm.

[[args]]
=== Utiliser des arguments et des options

Nous avons vu comment récupérer les arguments d'un script Node
en découvrant le <<../chapter-04/index.adoc#process,module `process`>>
au <<../chapter-04/index.adoc#,chapitre 4>>
— un des nombreux modules fournis avec chaque installation de Node.
Pour rappel, la variable `process.argv` est un tableau qui contient tous
les arguments passés au script principal :

[source,javascript]
.options/intro.js
----
include::{sourceDir}/options/intro.js[]
----

Ce qui donne le résultat suivant quand nous lançons ce script dans un terminal :

----
$ node options/intro.js --country FR --fast
[ '--country', 'FR', '--fast' ]
----

Ce tableau est un peu "léger" car il se contente de retourner les arguments,
sans compréhension de la logique recherchée.
C'est à nous de faire la démarche de dire que `FR` est une valeur
associée à `--country`.

Dans le contexte des outils en ligne de commande,
les arguments et les options sont des paramètres qui sont interprétées
par le programme pour contextualiser son action.
Ils fonctionnent un peu comme des arguments de
<<../chapter-03/index.adoc#function,fonction>> et des paramètres d'URL.

L'enjeu des arguments et des options est de les
*transformer en une structure de données* afin de les passer en tant
que paramètres d'une fonction.

[format="csv", separator=";", options="header", cols="1,2,2"]
.Représentation des arguments et des options entre un outil en ligne de commande, une fonction et une URL.
|===
;Options;Arguments
Fonction; `prog({country: 'FR', 'fast': true})`; `prog('FR', 'fast')`
Ligne de commande; `prog --country FR --fast`; `prog FR fast`
URL; `prog/?country=FR&fast=true`; `prog/FR/fast`
|===

Nous allons utiliser le module npm _minimist_ ([URL]#https://npmjs.com/minimist#)
dans les exemples suivants.
Il prend en charge la complexité de l'interprétation de `process.argv` et je
le trouve robuste, bien testé et minimaliste.

[NOTE]
.[RemarquePreTitre]#Histoire# Au commencement était `getopt`
====
`getopt` ([URL]#https://linux.die.net/man/3/getopt#) est le programme Linux
sur lequel se calque une très grande majorité des exécutables en ligne de
commande.
====

[[args.options]]
Commençons par les *options* et voyons ce que _minimist_ affiche :

----
$ node options/parse.js --country FR --fast
{ _: [], country: 'FR', fast: true }  # <1>
----
<1> La valeur `_` contient les <<args.arguments,arguments>> d'exécution — nous y reviendrons.

Les options sont adaptées pour *nommer des paramètres facultatifs* dont
l'ordre n'a pas d'importance, sous forme d'un "interrupteur" dans le cas
d'un booléen ou d'une valeur — nombre ou chaîne de caractères, peu importe.

[source,javascript]
.options/parse.js
----
include::{sourceDir}/options/parse.js[]
----

Les options s'écrivent sous une *forme raccourcie* (_alias_).
Elle signalée avec un seul tiret et elle réduit l'encombrement visuel
d'une commande :

----
$ node options/alias.js <i>-c</i> FR
{ _: [], c: 'FR', country: 'FR' }
----

[source,javascript]
.options/alias.js
----
include::{sourceDir}/options/alias.js[]
----
<1> Définition de l'option `-c` en tant qu'alias de `--country`.
<2> L'affichage représenté à la fois la valeur de l'option et la valeur de l'alias.

La lecture est rendue plus difficile pour celui ou celle qui n'a pas lu
le manuel d'utilisation en détail — ce qui est souvent le cas, surtout
pour des personnes qui découvrent un nouveau logiciel.

J'ai tendance à utiliser les alias pour les options principales ou importantes.
Je privilégie la forme longue dans les exemples et dans la documentation
afin d'augmenter les chances de compréhension.

Les *valeurs par défaut* simplifient le paramétrage en rendant certaines
valeurs implicites :

----
$ node options/defaults.js --fast
{ _: [], country: 'FR', fast: true } # <1>
----
<1> La valeur `country` affiche une valeur alors que nous ne l'avons pas spécifié dans la commande.

L'enjeu réside alors dans l'utilisation des valeurs à bon escient, pour
que le programme fasse ce qui est attendu d'un point de vue utilisateur.
Le paramétrage est similaire à celui des _alias_ :

[source,javascript]
.options/defaults.js
----
include::{sourceDir}/options/defaults.js[]
----
<1> L'option `--country` aura `FR` comme valeur par défaut.

Un autre concept utile est celui des *types*.
Nous définissons explicitement nos attentes sur ce que telle ou telle option
est censée recevoir :

----
$ node options/types.js --country --fast furious  # <1>
{ _: [ 'furious' ], fast: true, country: '' }
$ node options/types.js --country FR
{ _: [], fast: false, country: 'FR' }             # <2>
----
<1> Omission de la valeur de `--option` et tentative d'assignation de valeur à l'option booléenne `--fast`.
<2> Une vaut implicitement `false` par défaut quand elle est typée comme booléenne.

L'exemple précédent renforce nos attentes : l'option `--country` sans valeur
ne sera pas comprise comme un booléen et au contraire, l'option booléenne `--fast`
n'accepte pas de valeur — cette dernière est interprétée
comme un <<args.arguments,argument>>.
Nous allons nous y intéresser de suite après.

[source,javascript]
.options/types.js
----
include::{sourceDir}/options/types.js[]
----

[horizontal]
.Synthèse des différentes formes d'options.
`--country FR`::
`-c FR`::
  Un nombre ou une chaîne de caractères.
`--country FR UK`::
`--country FR --country UK`::
  Un ou ou plusieurs nombres ou chaînes de caractères.
`--fast`::
`--no-fast`::
`-f`::
  Un booléen dont la valeur vaut `true`.
  La valeur vaut `false` quand l'option débute avec `no-`. +
  Utile quand nous avons besoin d'activer ou de désactiver quelque chose.
`--verbose --verbose`::
`-vv`::
  Certaines librairies utilisent la répétition d'un booléen comme un compteur.
  Auquel cas, la notation `--verbose --verbose` correspondrait à la
  valeur `{verbose: 2}`. +
  Utile pour gérer la gradation d'une option comme la verbosité de l'affichage
  logs par exemple.

[[args.arguments]]
Les arguments sont adaptés à des situations où
*une ou plusieurs valeurs sont obligatoires*, n'ont pas besoin d'être nommées et
pour en accepter un nombre arbitraire.
Si les valeurs ne correspondent pas à une liste, le positionnement des arguments
est important car il détermine leur identification.
Les arguments se prêtent particulièrement bien à exprimer
une liste de fichiers ou d'identifiants.

----
$ node options/parse.js Europe/London
{ _: [ 'Europe/London' ] }
----

Le paramètre passé en argument est l'expression d'un fuseau horaire
selon l'organisme de standardisation _IANA_ ([URL]#https://www.iana.org/time-zones#).
Une liste de fuseau se trouve sur [URL]#https://time.is/time_zones#. +
L'idée est d'afficher l'heure courante selon le fuseau horaire donné en argument.
C'est un paramètre obligatoire qu'il n'est pas nécessaire de nommer :

----
$ node options/timezone.js Europe/London
22:29
$ node options/timezone.js America/New_York
17:29
$ node options/timezone.js Indian/Antananarivo  # <1>
17/6/2018, 00:36
----
<1> Fuseau horaire de l'île de Madagascar.

Nous pouvons travailler avec les fuseaux horaires sans module additionnel,
grâce à la fonctionnalité de
<<../chapter-03/index.adoc#intl.datetimeformat,formatage internationalisé>>
(cf. <<../chapter-03/index.adoc#,chapitre 3>>) :

[source,javascript]
.options/timezone.js
----
include::{sourceDir}/options/timezone.js[]
----
<1> Nous assignons à `timezone` la première valeur du tableau d'arguments.
<2> Configuration des préférences d'affichage de l'heure.
<3> Utilisation de la méthode `toLocaleDateString()` avec nos options pour afficher la date courante.

Cet exemple se transformerait de la manière suivante si nous souhaitions
étendre l'affichage de l'heure à autant de fuseaux horaires que voulus :

----
$ node options/timezones.js Europe/London America/New_York
Europe/London : 22:29
America/New_York : 17:29
----

[source,javascript]
.options/timezones.js
----
include::{sourceDir}/options/timezones.js[]
----
<1> Nous constituons un nouveau tableau en itérant sur chacun des arguments.
<2> Valeur de retour utilisée dans le nouveau tableau `output` — cf. <<../chapter-03/index.adoc#array,chapitre 3>>.
<3> Le tableau est joint pour constituer une chaîne de caractères multilignes.

Ce script accepte un nombre indéfini d'arguments et son temps d'exécution
dépendra de la longueur de cette liste.
Elle n'a d'ailleurs pas forcément à être connue à l'avance et les valeurs
s'obtiennent dynamiquement, en les sourçant depuis ce fichier, par exemple :

[source,text]
.options/zones.txt
----
include::{sourceDir}/options/zones.txt[]
----

Le contenu du fichier s'obtient d'une traite en bash avec l'utilisation combinée
de la capture de sortie (`$(...)`) et de l'opérateur de redirection `<` :

----
$ node options/timezones.js $(< options/zones.txt)
Europe/London : 22:29
America/New_York : 17:29
----

C'est simple et ça fonctionne jusqu'à un certain point : le fichier doit être lu
dans son intégralité et copié entièrement dans la mémoire de Node avant d'en
faire quelque chose.
Une approche plus économique est d'utiliser les
<<../chapter-03/index.adoc#stream,streams>> (cf. <<../chapter-03/index.adoc#,chapitre 3>>.
Nous parlerons plus en détail de cette technique dans la section
<<streaming,passer le contenu complet d’un fichier en paramètre>> de ce même
chapitre.

[horizontal]
.Synthèse des différentes formes d'arguments.
`prog [argument1, ...]`::
  L'ordre de placement étant important, les arguments facultatifs doivent
  être placés à droite des arguments obligatoires.
`prog sous-commande [argument1, ...]`::
  C'est un cas particulier pour découper un programme complet en plusieurs
  domaines d'action. +
  Le premier argument est alors utilisé
  Les sous-commandes ne gèrent pas forcément les mêmes arguments et options.

////
[[args.subcommand]]
c'est l'équivalent d'une _route_ dans une application
////

Les arguments et les options ne sont *pas adaptées pour véhiculer le contenu*
d'un fichier, ou toute autre donnée volumineuse.
Deux solutions s'offrent à nous : <<streaming,diriger le contenu>> vers
le programme (_streaming_) ou renseigner le chemin d'accès à ce contenu
(URL, chemin d'accès, etc.).

[[colours]]
=== Améliorer la lisibilité grâce aux couleurs

- chalk
- un autre module plus fonctionnel
- ANSI (sous Windows c'est différent je crois)

https://www.npmjs.com/package/supports-color

[[questions]]
=== Demander une série d'informations

- https://www.npmjs.com/package/inquirer
- https://www.npmjs.com/package/promptly

[[progress]]
=== Informer de la progression

- https://www.npmjs.com/ansi-escapes
- https://www.npmjs.com/package/ora
- https://www.npmjs.com/package/progress-string

[[update]]
=== Inviter à mettre à jour le module

- update-check

[[tables]]
=== Afficher des informations tabulaires

- https://www.npmjs.com/package/table


[[tests]]
== Vers un code testable et réutilisable

Obtenir la surface la plus faible possible entre son code et la lecture
des arguments.

[[interface]]
=== Réduire la surface de code spécifique à la ligne de commande

réduire le plus possible ce qu'il y a dans un fichier exécutable
pour tester le plus facilement

((exemple inDir outDir -- réutiliser du code métier))

idéalement ce qui est dans le `main` est consommé par le `bin`

[[tests.interface]]
=== Tester le code partagé

avec les outils habituels

[[tests.cli]]
=== Tester l'exécutable

plus dur, plus de code à écrire

- à la main avec spawn/exec
- tape-spawn
- cli-tester
- coffee

[[doc]]
=== Documenter notre programme

- README
- prog --help

[[advanced]]
== Aller plus loin

[[application]]
=== Utilisation d'un framework d'application en ligne de commande

ça fait beaucoup de choses qu'on a fait bout par bout
pratique si on a besoin de tout utiliser en même temps
équivalent des express & co pour le web (cf. chapitre 7)

- yargs
- commander
- un autre truc plus léger

[[wildcard]]
=== Maîtriser le vocabulaire d'expansion de chemins (_wildcard_)

[[streaming]]
=== Passer le contenu complet d'un fichier en paramètre

utilisation des streams

[[packaging]]
=== Rendre le programme indépendant de Node

packager l'application (https://www.npmjs.com/package/pkg).

[[declarative]]
=== Templating et interfaces déclaratives

- https://www.npmjs.com/package/blessed
- https://www.npmjs.com/package/react-blessed

== Conclusion

TBD.
