:chapterNumber: 8
:chapterId: chapter-08
:sourceDir: ./examples
:nodeCurrentVersion: v10
:npmCurrentVersion: v6
:sectnums:
:revdate: {docdate}
:imagesdir: {indir}
ifdef::env[]
:imagesdir: .
endif::[]

= Créer un outil en ligne de commande

TBD.

====
.Sommaire
- TBD.
====

[abstract]
--
TBD.
--

include::../docs/tip-versions.adoc[]

install global : pour quelqu'un qui n'a pas besoin de l'inclure dans un projet.
Être autonome.
En faire un outil système.
Taper la commande sans avoir à se soucier d'autre chose.

utilisation : le nom c'est le même.
Plus logique.
Plus facile à retenir.
Mais ça peut se changer.

[[start]]
== Créer un script exécutable

[[script]]
=== Au départ, un simple script Node

Dans le répertoire `./bin` parce que c'est la convention

> Il faudra faire le lien avec le package.json

----
$ node bin/fichier.js
----

include::../docs/tip-examples.adoc[]

[[permissions]]
=== Modifier les permissions du script

pour le rendre exécutable (Linux et macOS)

----
$ chmod +x bin/fichier.js
----

Warning : +x pour tout le monde

[[shebang]]
=== Préciser le contexte d'exécution (_shebang_)

Il faut parler à bash. `#!` sert à ça.

Chemin absolu vers exécutable.
`/usr/bin/env` vs `which` vs `/usr/bin/node` ?

> Runs a program in a modified environment.
(chercher plus sur pourquoi env)

[[package.json]]
=== Faire le lien avec un module npm

Champ `bin`

[[install]]
=== Tester une installation globale, localement

----
$ npm i -g .
----

Prend en compte les changements locaux.

[[interface]]
=== Vers un code testable et réutilisable

Obtenir la surface la plus faible possible entre son code et la lecture
des arguments.

réduire le plus possible ce qu'il y a dans un fichier exécutable
pour tester le plus facilement

((exemple inDir outDir -- réutiliser du code métier))

idéalement ce qui est dans le `main` est consommé par le `bin`

[[interactive]]
== Du script au programme interactif

[[options]]
=== Utiliser des options et arguments

`process.argv`

Tableau qui contient toutes les chaines de caractère utilisées pour lancer la commande.

(héritage UNIX).

`process.argv.slice(2)`

Créer des variables explicites au lieu de `process.argv[2]`.

Et la mémoire ?
Le script utilisera la mémoire disponible, à concurrence des autres applications qui tournent sur la même machine
Sur un Raspberry Pi, y'a moins de mémoire donc on peut atteindre plus rapidement des limites si les fichiers dépassent les capacités (centaine de Mo — vs. plus Go sur des ordinateurs modernes)

[[colours]]
=== Améliorer la lisibilité grâce aux couleurs

- chalk
- un autre module plus fonctionnel
- ANSI (sous Windows c'est différent je crois)

[[questions]]
=== Demander une série d'informations

- demand
- <insérer un module npm qui fait ça bien>

[[progress]]
=== Informer de la progression

- readline
- spinner
- progressbar

[[update]]
=== Inviter à mettre à jour le module

- update-check


[[tests]]
== Tester son code

[[tests.interface]]
=== Seulement l'interface

avec les outils habituels

[[tests.cli]]
=== Tester l'exécutable

plus dur, plus de code à écrire

- à la main avec spawn/exec
- tape-spawn
- cli-tester
- coffee

[[advanced]]
== Aller plus loin

[[application]]
=== Utilisation d'un framework d'application en ligne de commande

ça fait beaucoup de choses qu'on a fait bout par bout
pratique si on a besoin de tout utiliser en même temps
équivalent des express & co pour le web (cf. chapitre 7)

- yargs
- commander
- un autre truc plus léger

[[streaming]]
=== Lire et écrire des données en continu

utilisation des streams

[[packaging]]
=== Rendre le programme indépendant de Node

packager l'application (https://www.npmjs.com/package/pkg).

[[declarative]]
=== Templating et interfaces déclaratives


== Conclusion

TBD.
