:chapterNumber: 7
:sourceDir: ./examples
:sourceSample: TODO.js
:nodeCurrentVersion: v6
:npmCurrentVersion: v4
:sectnums:
:revdate: {docdate}
:imagesdir: {indir}
ifdef::env[]
:imagesdir: .
endif::[]

= Héberger, déployer et monitorer


====
.Sommaire
- TBD
====

include::../resources/tip-versions.adoc[]
include::../resources/tip-examples.adoc[]

toc::[]

== Cycle de vie d'une application Node

=== Configuration

- fichiers
- variables d'environnement
- services type etcd

=== Exécution

TBD.

=== Persistence des données

TBD.

=== Une application = plusieurs services

TBD.


=== Scénarios possibles en fonctionnement

TBD.


== Héberger une application Node

=== Directement sur le port 80

TBD.

tl;dr ne pas le faire

=== Reverse Proxy

TBD.

- Apache
- nginx

=== Gestionnaire d'applications

TBD.

- Phusion Passenger

=== Hébergement mutualisé

TBD.

- Alwaysdata

=== Plate-forme de services (_Platform As A Service_)

TBD.

- Heroku
- Clever Cloud

_Foreman_ est un programme écrit en Ruby.
Il est destiné à gérer les multiples processus d'une même application. +
C'est l'outil de déclaration de services utilisé par la plateforme _Heroku_.

Vos différents processus sont à déclarer dans un fichier `Procfile`, somme toute assez simpliste :

[source]
.Procfile
----
web: node www.js
api: PORT=$PORT node api.js
worker: node bin/cli.js --retries 3
----

Le précédent exemple fait état de trois processus à démarrer, dont certains avec des arguments spécifiques.

La commande suivante démarrera ces trois services, créera deux processus pour le module `api.js` en leur attribuant automatiquement un port différent grâce à :

----
foreman start -c api=2
----

[TIP]
.[RemarquePreTitre]#Outil# foreman
====
D'autres fonctionnalités et paramètres de configuration sont expliqués dans la documentation officielle du projet :

- [URL]#https://ddollar.github.io/foreman/#
- [URL]#https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-a-procfile#
====

=== Invocation éphémère (_Function as a Service_)

TBD.

- Lambda

=== Amazon Web Services (_AWS_)

TBD.

- AMI EC2
- Beanstalk

== Déploiement d'une application Node

=== Vers un déploiement automatisé

TBD.

=== Déploiement immutable

TBD.

- deb/etc.
- tar

=== Le cas des dépendances privées

TBD.

- git+ssh
- private npm

=== Scripter le déploiement

TBD.

- Ansible

=== Gestion des services

TBD.

_Upstart_ est l'outil de gestion de processus de la distribution Linux Ubuntu.
Sa configuration est une des plus faciles à apprendre :

[source]
./etc/init/your-app
----
start on runlevel [2345] and net-device-up IFACE=eth0

exec /usr/bin/node /path/to/your/app.js
----

Cette configuration ultra simpliste décrit la commande à exécuter et quand lancer automatiquement le service.
Dans ce cas, au démarrage du système, une fois le réseau disponible sur l'interface `eth0`.

[TIP]
.[RemarquePreTitre]#Outil# Upstart
====
Une introduction ainsi qu'une documentation détaillée d'_Upstart_ est disponible à l'adresse suivante :

- [URL]#https://doc.ubuntu-fr.org/upstart# (en français)
- [URL]#http://upstart.ubuntu.com/cookbook/# (en anglais)
====

L'apprentissage et le débogage de tels scripts peut se révéler fastidieuse et rébarbative… _foreman_ dispose d'une fonctionnalité d'export adressant le problème.
Pensez-y !

== Monitorer une application

=== Déceler les erreurs et exceptions

TBD.

=== Surveiller la santé de l'application

TBD.

=== Identifier les problèmes de performance

TBD.

== Conclusion

TBD.
