:chapterNumber: 6
:sourceDir: ./examples
:sourceSample: TODO.js
:nodeCurrentVersion: v6
:npmCurrentVersion: v4
:sectnums:
:revdate: {docdate}
:imagesdir: {indir}
ifdef::env[]
:imagesdir: .
endif::[]

= Héberger, déployer et monitorer


[CAUTION]
====
Ce chapitre est en cours de rédaction.
====


====
.Sommaire
- Cycle de vie d'un processus Node
- Héberger sur une machine administrée
- Déployer sur une plateforme de services
- Gestion des dépendances privées
- Stratégies d'installation
====

include::../resources/tip-versions.adoc[]
include::../resources/tip-examples.adoc[]

toc::[]

== Cycle de vie d'un processus Node

=== Configuration

- fichiers
- variables d'environnement
- services type etcd

=== Démarrage

TBD.

=== Exécution

TBD.

=== Orchestration des services

Nous venons de voir différentes manières d'instancier des applications… mais aucune d'entre elles n'est vraiment satisfaisante en terme de résistance.
À la moindre erreur, tout tombe !

C'est sans compter sur le fait que vos modules contiendront plusieurs serveurs ou _daemons_ à initialiser… voire encore, vous aurez plusieurs serveurs ou _daemons_ répartis dans plusieurs projets différents.

_forever_ est un module populaire dédié à la gestion et au monitoring de process et pas spécifiquement Node d'ailleurs. +

La commande suivante aura pour effet de démarrer et de placer le processus `server.js` — un _daemon_.

----
$ forever start server.js
----

Il y a deux gains évidents à cet outillage :

- le processus persistera à la fermeture de la session ;
- la gestion centralisée des processus.

_forever_ créera autant de processus que vous le désirez tout en fournissant un interface pour redémarrer les services, les arrêter, consulter leur logs ou encore afficher à l'écran l'ensemble processus actifs :

----
$ forever list
info:    Forever processes running
data:        uid  command                  script  pid   logfile           uptime
data:    [0] _sHw /usr/bin/node www.js     15594   15610 /var/log/_sHw.log 0:0:1:59.865
data:    [1] vytX /usr/bin/node api.js     15655   15671 /var/log/vytX.log 0:0:1:38.980
data:    [2] MOrx /usr/bin/node bin/cli.js 15769   15785 /var/log/MOrx.log 0:0:0:57.960
----

Cerise sur le gâteau : une application qui plante sera relancée automatiquement par _forever_.
À vous ensuite d'inspecter les logs d'erreurs et de mettre en place un mécanisme d'alerte pour ne pas faire perdurer ces exceptions.

Toutefois, revers de la médaille : il vous faudra exécuter _forever_ autant de fois qu'une application a de processus à démarrer.

[TIP]
.[RemarquePreTitre]#Outil# forever
====
Une documentation détaillée accompagnée d'exemples est disponible sur le dépôt GitHub du projet :

- [URL]#https://github.com/nodejitsu/forever#
====

_Foreman_ est un programme écrit en Ruby.
Il est destiné à gérer les multiples processus d'une même application. +
C'est l'outil de déclaration de services utilisé par la plateforme _Heroku_.

Vos différents processus sont à déclarer dans un fichier `Procfile`, somme toute assez simpliste :

[source]
.Procfile
----
web: node www.js
api: PORT=$PORT node api.js
worker: node bin/cli.js --retries 3
----

Le précédent exemple fait état de trois processus à démarrer, dont certains avec des arguments spécifiques.

La commande suivante démarrera ces trois services, créera deux processus pour le module `api.js` en leur attribuant automatiquement un port différent grâce à :

----
foreman start -c api=2
----

[TIP]
.[RemarquePreTitre]#Outil# foreman
====
D'autres fonctionnalités et paramètres de configuration sont expliqués dans la documentation officielle du projet :

- [URL]#https://ddollar.github.io/foreman/#
- [URL]#https://devcenter.heroku.com/articles/getting-started-with-nodejs#define-a-procfile#
====

Il ne nous manque qu'une seule chose désormais : pouvoir démarrer nos processus avec le système d'exploitation, après un démarrage ou redémarrage.
Un bénéfice non-négligeable de l'intégration avec le système d'exploitation est la combinaison avec les outils de monitoring et d'agrégation de logs.

_Upstart_ est l'outil de gestion de processus de la distribution Linux Ubuntu.
Sa configuration est une des plus faciles à apprendre :

[source]
./etc/init/your-app
----
start on runlevel [2345] and net-device-up IFACE=eth0

exec /usr/bin/node /path/to/your/app.js
----

Cette configuration ultra simpliste décrit la commande à exécuter et quand lancer automatiquement le service.
Dans ce cas, au démarrage du système, une fois le réseau disponible sur l'interface `eth0`.

[TIP]
.[RemarquePreTitre]#Outil# Upstart
====
Une introduction ainsi qu'une documentation détaillée d'_Upstart_ est disponible à l'adresse suivante :

- [URL]#https://doc.ubuntu-fr.org/upstart# (en français)
- [URL]#http://upstart.ubuntu.com/cookbook/# (en anglais)
====

L'apprentissage et le débogage de tels scripts peut se révéler fastidieuse et rébarbative… _foreman_ dispose d'une fonctionnalité d'export adressant le problème.
Pensez-y !

Nous avons progressivement outillé l'exécution et la prise en charge de nos applications.
Maintenant intéressons-nous aux impacts de la modification d'une application en service.

=== Arrêt involontaire

TBD.

=== Arrêt volontaire

TBD.

== Héberger sur une machine administrée

=== Exposer le port 80

TBD.

=== Derrière Apache HTTP Server

TBD.

=== Derrière NGINX

TBD.

=== Phusion Passenger

TBD.

== Déployer sur une plateforme de services

=== Heroku

TBD.

=== Digital Ocean

TBD.

=== OVH

TBD.

=== Clever Cloud

TBD.

=== Amazon Elastic Beanstalk

TBD.


== Gestion des dépendances privées

=== Via git+ssh

TBD.

=== Via un registre privé

- npmE / private npm
- Bintray
- sinopia

== Stratégies d'installation

=== npm install

- `git clone && npm install --production`

=== npm pack

TBD.

=== Avec Docker

TBD.
