parserOptions:
  sourceType: module

globals:
  URL: true   # Delete when eslint is okay with URL being a global in Node 10.0.0
              # cf. https://github.com/eslint/eslint/issues/10284

rules:
  strict: off
  handle-callback-err: off
