:nodeVersion: v0.12
:revisionYear: 2015
:sourceDir: ./examples/src
:imagesdir: {indir}
ifdef::env[]
:imagesdir: .
endif::[]

== [ChapitreNumero]#4# Au service du développement frontend

Les chapitres précédents ont démontré l'utilité de Node pour la création de modules réutilisables ainsi que pour le développement d'applications et d'utilitaires.

Ce chapitre nous apprendra le _rôle utilitaire_ de Node pour le développement _frontend_.
C'est à dire l'utilisation de Node comme outil de productivité et d'automatisation du développement de composants Web.

====
.Sommaire
- Choisir un gestionnaire de paquets
- Un outillage sur mesure
- Automatiser les projets
- Partager du code entre Node et le navigateur
- Tester dans le navigateur
====

Node en tant que plate-forme ne fournit rien de spécial à part des fondations communes avec les navigateurs Web.
C'est la richesse et la versatilité de l'écosystème npm qui nous permet de mieux outiller nos projets.

Pour rappel, avant l'apparition de Node, rare était l'outillage n'imposant pas une plateforme de développement entière (comme _sprockets_ et _assetic_ dans les univers Ruby et PHP).
Il fallait se contenter de programmes tels que _YUICompressor_, _Google Closure Compiler_ ou encore _pngquant_.
Leur installation diffère selon les systèmes d'exploitation, quand ils sont multi-plateformes.
C'est sans parler de leur intégration et de leur systématisation au sein des projets.

Bref c'était lourd et compliqué à moins de disposer d'une infrastructure industrialisée. +
Node simplifie tout, de la récupération des bibliothèques tierces à la compilation, optimisation et aux tests de vos composants Web.

=== Gestion des dépendances

Avant Node, l'obtention d'une bibliothèque se faisait en allant sur son site Web respectif puis en téléchargeant une archive avant de la décompresser dans votre répertoire de travail.
C'est sans compter sur les téléchargements sur-mesure dont il fallait mémoriser les options de mise à jour en mise à jour.

Tout ceci appartient au passé grâce aux gestionnaires de paquets.
Ils rendent explicites la liste des dépendances, le spectre des versions compatibles ainsi que l'automatisation des opérations d'installation et de mises à jour.

==== npm

_npm_ est le gestionnaire de dépendances par défaut de Node.
Pourquoi en parler s'il ne fonctionne que pour Node ?
Car contrairement aux à prioris, *npm ne se limite pas qu'à Node*.

Quelles sont les raisons de choisir npm comme gestionnaire de dépendances _frontend_ ?

- déclaration explicite des points d'entrée via la propriété _main_ du fichier _package.json_ ;
- inclusion des dépendances avec la syntaxe _CommonJS_ ;
- transformation des appels _CommonJS_ en modules _AMD_ ou pur ECMAScript (_vanilla ECMAScript_) ;
- utilisation du même outil de dépendance, indépendamment du contexte d'exécution de l'application ;
- c'est le meilleur moyen d'atteindre l'_isomorphisme applicatif_ (lire _Vers un code isomorphique et modulaire_ dans ce même chapitre).

L'exemple suivant illustre deux moyens d'inclure jQuery dans une page HTML, via une simple balise script ou via la syntaxe AMD :

[source,html]
.snippets/dependency-npm.html
----
include::{sourceDir}/snippets/dependency-npm.html[]
----

Rien de spécial à signaler, si ce n'est que cela nous force à exposer le contenu du répertoire `node_modules` de notre projet.

L'utilisation de npm nécessitera une étape de compilation dans les cas où les dépendances ne proposent pas de code directement intelligible par les navigateurs Web.
Ce sera le cas si les dépendances ne proposent que des modules CommonJS (faisant appel à `require()`), sans artéfacts précompilés.
Dans le précédent exemple jQuery propose ces artéfacts dans un répertoire `dist`.

Un second frein est l'effort de simplification et de vérification de l'arbre de dépendances pour éviter les redondances.

----
.
└── node_modules
    ├── moduleA
    │   └── node_modules
    │       └── jquery
    └── moduleB
        └── node_modules
            └── jquery
----

Le schéma précédent illustre la situation où deux modules différents dépendent tous deux de jQuery.
La structure de dépendances en arbre de npm n'est pas optimisée pour des performances Web. 
Elle n'est d'ailleurs pas conçue pour être exposée telle quelle via un serveur HTTP, sauf pour des besoins de prototypage rapide.

L'utilisation de `npm dedupe` peut toutefois simplifier la structure de l'arbre.
Notre exemple précédent sera optimisé de la sorte :

----
.
└── node_modules
    ├── jquery
    ├── moduleA
    └── moduleB
----

Inconvénient : cela cassera tout appel de chemin en dur dans `moduleA` et `moduleB` et nécessitera d'utiliser le mécanisme de résolution de chemin de CommonJS. +
Nous verrons par la suite que ces inconvénients n'en sont pas vraiment, et que les mécanismes de compilation reposant sur CommonJS sont très largement bénéficiaires pour une chaîne de compilation entièrement automatisée.

[WARNING]
.[RemarquePreTitre]#Windows# NTFS et ses 255 caractères
====
Le système de fichiers NTFS limite la longueur d'un chemin à 255 caractères. +
npm gérant les dépendances sous forme d'arborescence de répertoires, il se pourrait que vous atteigniez cette limite en cas de profondeur prononcée et de longs noms de modules.

Si Windows est votre plateforme de développement principale ou votre environnement de déploiement, optez pour un gestionnaire de dépendances à plat tel que _bower_ (voir ci-après).
====

Nous verrons davantage d'exemples, plus complets et variés dans la section _Vers un code isomorphique et modulaire_.

==== bower

_bower_ est un gestionnaire de dépendances entièrement dédié aux composants _frontend_.
Son interface est très proche de celle la commande npm.
Les dépendances sont quant à elles listées dans un fichier `bower.json`.

----
npm install -g bower
bower init
bower install --save jquery
----

Si les deux gestionnaires de modules sont à ce point similaires, quelles seraient les raisons d'opter pour bower ?

- sa capacité à inclure des dépendances n'ayant pas déclarées de fichier `bower.json` ;
- sa structure à plat, facile à lire ;
- l'absence de phase de compilation obligatoire ;
- la séparation explicite des componsants _frontend_ des composants _backend_.

Il a souvent été perçu comme plus légitime que npm pour les besoins _frontend_, ce dernier étant perçu comme étant exclusivement dédié aux dépendances Node.

L'exemple suivant illustre deux moyens d'inclure jQuery dans une page HTML, via une simple balise script ou via la syntaxe AMD :

[source,html]
.snippets/dependency-bower.html
----
include::{sourceDir}/snippets/dependency-bower.html[]
----

Derrière cette simplicité de prise en main, deux inconvénients se font ressentir à long terme :

- l'impossiblité d'inclure une dépendance sans en connaître le chemin exact ;
- la difficulté à produire des artéfacts optimisés depuis les sources des modules — certains ne fournissant que des artéfacts sans les sources originales.

Autrement dit, les avantages de bower font les inconvénients de npm et vice-versa. +
Démarrer par bower est probablement la solution la plus rapide pour élimiter l'acquisition manuelle des dépendances … mais les limites se feront sentir dès lors que les barrières entre _backend_ et _frontend_ se feront sentir.

==== Exposer un composant Web avec Node

Que vous utilisiez npm ou bower pour gérer vos dépendances, il peut arriver que vous ayiez besoin de les servir via HTTP.

Le _framework_ _express_ ([URL]#http://expressjs.com/#) met à disposition un mécanisme de _montage d'URL_.
En combinant ce mécanisme avec la méthode `express.static`, il devient alors possible d'exposer n'importe quel fichier ou répertoire en tant que ressource Web.

[source,javascript]
.snippets/npm-express.js
----
include::{sourceDir}/snippets/npm-express.js[]
----
<1> Rend accessible le fichier `jquery.js` à l'adresse `http://localhost:3000/assets/jquery.js` ;
<2> Rend accessible le répertoire `node_modules` à l'adresse `http://localhost:3000/assets`, et donc d'une autre manière, le fichier `jquery.js` à l'adresse `http://localhost:3000/assets/jquery/dist/jquery.js`.

Pour en savoir plus sur l'utilisation du _framework_ _express_, reportez-vous à la section _Application Web_ du chapitre 4.

=== Un outillage sur mesure

Qu'il s'agisse de vos propres composants ou de modules tiers, l'écosystème Node regorge d'utilitaires facilitant la vie de tout développeur _frontend_.

Outre l'uniformisation de l'installation de vos composants et dépendances, *vous rendez explicite et partagez le même processus* avec tous les membres de votre équipe.
Et même si vous êtes seul(e) sur le projet, vous construisez une documentation d'utilisation pour les prochaines personnes susceptibles de participer au projet.

Autre avantage indéniable : l'ubiquité des utilitaires.
S'ils peuvent être utilisés de manière indépendante, ils s'intègrent très bien avec des outils d'automatisation ou des _frameworks_ populaires.

Vous trouverez ci-après une suggestion non-exhaustive de modules utiles à tout développeur _frontend_.

==== Vérification syntaxique

La vérification syntaxique est un mécanisme s'assurant que votre code respecte la grammaire du langage associé.
Elle peut autant révéler des anomalies fondamentales (balise mal fermée, expression inconnue etc.) que renforcer des pratiques de programmation réduisant les erreurs potentielles lors de l'exécution du-dit code.

Il s'agit d'une excellente première étape avant d'introduire des tests unitaires ou fonctionnels.
C'est aussi une pratique rapide à mettre en œuvre — de préférence dès le début du projet — et poussant à harmoniser les pratiques de développement au sein d'un group d'individus.

Les modules à disposition dans npm vous permettront de couvrir vos fichiers CSS, HTML et ECMAScript bien sûr !

*htmlhint* ([URL]#https://npmjs.com/htmlhint#) est un outil en ligne de commande vérifiant la structure de vos documents HTML.
Il rapporte les doublons d'attributs `id`, la présence de paires de balises mal formées, l'absence de balise fermante ou encore l'existance de chaînes de charactère non-imprimables dans des attributs critiques, entre autre.

Prenons en exemple le document suivant :

[source,html]
.snippets/sample.html
----
include::{sourceDir}/snippets/sample.html[]
----

Une lecture distraite pourrait nous faire passer à côté des erreurs mais également des inconsistances de programmation.
Sur un document plus réaliste, et donc volumineux, avec de fréquents changements, autant oublier la vérification manuelle.

L'exéction de *htmlhint* avec ses règles par défaut remontera les alertes suivantes :

----
$ npm run lint-html
src/snippets/sample.html:
line 1, col 1: Doctype must be first.
line 8, col 10: Id redefinition of [ btn ].
line 10, col 3: Tagname [ BUTTON ] must be lower case.
line 10, col 10: The value of attribute [ class ] must closed by double quotes.
line 10, col 52: Tagname [ BUTTON ] must be lower case.
----

Si elle peuvent paraître opiniatres, sachez qu'elles n'ont pour seul but que de décider une bonne fois pour toute quelle attitude adopter : tout ou rien en miniscule, guillemets simples ou doubles, doctype explicite etc.

*eslint* ([URL]#https://npmjs.com/eslint#) est le meilleur outil de vérification syntaxique pour ECMAScript.
Il offre un niveau de souplesse extrême au niveau de la configuration des règles à appliquer (utilisation systématique de `use strict`, nombre maximum de paramètres de fonctions, objets non-déclarés, variables inconnues etc.). +
Il expose également une API relativement simple à utiliser pour y adjoindre vos propres règles.
Que vous pouvez ainsi partager ou pas, selon qu'il s'agisse de vos propres règles métier ou non.

Appliquons les règles par défault d'*eslint* sur le code existant d'un précédent exemple de ce même chapitre :

----
$ npm run lint-es
src/snippets/npm-express.js
1:0   error  Use the function form of "use strict"  global-strict
1:0   error  Strings must use doublequote           quotes
3:14  error  'require' is not defined               no-undef
3:22  error  Strings must use doublequote           quotes
4:11  error  'require' is not defined               no-undef
4:19  error  Strings must use doublequote           quotes
7:17  error  'require' is not defined               no-undef
7:33  error  Strings must use doublequote           quotes
8:27  error  '__dirname' is not defined             no-undef
8:38  error  Strings must use doublequote           quotes
8:44  error  Strings must use doublequote           quotes
8:50  error  Strings must use doublequote           quotes
10:8   error  Strings must use doublequote           quotes
11:8   error  Strings must use doublequote           quotes
----

La vérification syntaxique se plaint de l'utilisation globale de `use strict`, de l'utilisation des guillemets simples et de certaines fonctions de Node. +
Le nom de la règle _eslint_ en question est explicitée en fin de ligne, pour information ou pour aider à affiner votre configuration.

*eslint* lit le fichier de configuration `.eslintrc` pour adapter son comportement , placé à la racine de votre projet mais il est tout à fait possible de lui fournir un emplacement alternatif.
Dans mon cas, j'ai indiqué une préférence pour les guillemets simples ainsi qu'une déclaration globale de `use strict` :

[source,json]
.{empty}.eslintrc
----
include::{sourceDir}/../.eslintrc[]
----

Le niveau de sévérité de chaque règle peut être configuré à l'aide d'un nombre entier :

- `0` : règle désactivée ;
- `1` : affiche un avertissement ;
- `2` : affiche une erreur et termine le processus avec un code d'erreur.

Certaines règles demandent ou acceptent des arguments supplémentaires.
Ces arguments sont documentés dans le répertoire `lib/rules` de la bibliothèque _eslint_ mais aussi sur son site Web.

*csslint* ([URL]#https://npmjs.com/csslint#) est un outil de vérification syntaxique de feuilles de style CSS.
Il a été créé par deux anciens ingénieurs de _Yahoo!_.
Leurs anciens travaux dans le domaine de la performance ont influencé l'architecture et le choix des règles par défaut.
Celles-ci peuvent d'ailleurs être étendues, moins aisément que pour *eslint* certes, mais suffisamment pour adapter l'outil aux besoins modernes, notamment ceux du Web mobile.

*csslint* fournit les mécanismes de vérification adéquats pour alerter de possibles effets de bord de _box model_, de déclaration incompatible de `@font-face`, de _vendor prefix_ dépréciés (voir plus loin la section _Optimisation du code_) ou encore de combinaisons de propriétés connues pour casser l'affichage dans certains navigateurs.

Prenons par exemple le fichier CSS suivant :

[source,css]
.snippets/sample.css
----
include::{sourceDir}/snippets/sample.css[]
----

*csslint* génèrera trois alertes en lisant le fichier `sample.css` et ce, même si celui-ci est syntaxiquement parfaitement valide :

----
$ csslint src/snippets/sample.css

csslint: There are 3 problems in snippets/sample.css.

sample.css
1: warning at line 4, col 11
Values of 0 shouldn't have units specified.
  border: 0px solid black;

sample.css
2: warning at line 4, col 3
Using height with border can sometimes make elements larger than you expect.
  border: 0px solid black;

sample.css
3: warning at line 6, col 3
Using height with padding can sometimes make elements larger than you expect.
  padding: 10px;
----

Si la présence d'une mesure en pixels n'est qu'une affaire de micro-optimisation, les deux autres erreurs sont nettement plus problématiques car elles impliquent un manque de consistance d'affichage, selon le navigateur effectuant le rendu. +
Éviter l'utilisation de ces cas limites évite également d'avoir à empiler des couches de CSS pouvant accentuer encore peu plus l'instabilité d'affichage.


*doiuse* ([URL]#https://npmjs.com/doiuse#) est un utilitaire qui se repose sur la base de données de [URL]#caniuse.com#.
Il vous alerte des possibles incompatibilités de syntaxe en fonction de la compatibilité désirée avec une liste de navigateurs web définie par vos soins.
Cette liste peut aussi bien concerner des versions spécifiques ou encore cibler en fonction leurs parts de marché.

L'exemple suivant illustre les alertes relevées par _doiuse_ dans le cas d'une recherche de compatibilité avec Internet Explorer 6 et Internet Explorer 7 :

----
$ doiuse -b 'ie < 8' src/snippets/sample.css
src/snippets/sample.css:1:1: CSS 2.1 selectors not supported by: IE (6)
src/snippets/sample.css:8:1: CSS 2.1 selectors not supported by: IE (6)
src/snippets/sample.css:12:1: CSS3 Transitions not supported by: IE (6,7)
src/snippets/sample.css:14:1: CSS 2.1 selectors not supported by: IE (6)
----


==== Minification du code

Commentaires, indentations ou encore noms de variables : tout ça occupe de la place, donc des caractères textuels et donc des octets de bande passante.

Sans outillage, l'optimisation repose littéralement entre les mains des développeurs.
Ces derniers doivent alors compromettre lisibilité et maintenabilité au profit de quelques kilo-octets. +
Ce que nous chercherons à tout prix à ne pas sacrifier.

Les minifieurs mettent en œuvre différentes techniques pour réduire cette occupation d'espace :

- suppression des commentaires et caractères non-significatifs ;
- renommage de variables ;
- factorisation d'occurences multiples similaires ;
- suppression des instructions relatives au débogage/développement ;
- suppression de code mort.

Ces différentes techniques de minification chercherons à préserver l'intégrité du fonctionnement ou de l'apparence de vos programmes.
Un avertissement vous préviendra du contraire le cas échéant.

*cssmin* ([URL]#https://npmjs.com/cssmin#) est un portage ECMAScript du compresseur CSS _YUICompressor_ développé par la compagnie _Yahoo!_ à la fin des années 2000. +
L'approche de *cssmin* consiste principalement à supprimer les caractères et commentaires non-significatifs.
Il ne cherche pas à faire davantage que son homologue originel.

*cssmin* est donc un outil simple, exposant un exécutable système ainsi qu'un module Node.
Il ne fournit en revanche aucun support pour les _Source Maps_. Il vous faudra reposer sur l'outillage proposé par les navigateurs Web modernes pour le débogage (reformatage du code, inspection des propriétés etc.).

.Exemples d'utilisation de *cssmin*
----
cssmin src/snippets/sample.css > sample.min.css # <1>

cat src/snippets/sample.css | cssmin | wc -c | awk '{print $1}' # <2>
----
<1> Exporte le résultat de la minification dans le fichier `sample.min.css`; 
<2> Utilisation des *pipes* UNIX pour afficher le nombre de caractères d'une version minifiée de `sample.css`.

**UglifyJS** ([URL]#https://npmjs.com/uglify-js2#) est un des premiers compresseurs à utiliser une  représentation syntaxique en arbre (_Abstract Syntax Tree_ — _AST_) en lieu et place des classiques optimisations à coups d'expressions régulières.

Cette méthode permet d'élargir les perspectives de la compression via de la réécriture de code :

- _hoisting_ des variables (remontée de leur déclaration en début de _scope_) ;
- combinaison des déclarations de variables ;
- factorisation des valeurs de variables ;
- réécriture partielle d'expressions ;
- injection en ligne du contenu de variables.

*UglifyJS* s'utilise de manière autonome, en ligne de commande ou via son API ECMAScript, mais aussi par le biais de plugins grunt, gulp et browserify (uglifyify et minifyify). +
Un exemple plus concret est abordé dans la section _Automatisation des tâches avec Grunt_.

==== Optimisation du code

Parce qu'optimiser le poids ne suffit pas, certains outils et compresseurs proposent de réécrire une partie de votre code.
Ces optimisations seraient souvent complexes à imaginer et couteuses en temps, à répéter le geste et en maintenance.

La majorité des optimiseurs suggérés vous inciteront à suivre la voie des standards.
Vous écrivez du code orienté vers le long terme et les outils se chargent du fardeau de la compatibilité avec le quotidien. +
De ce fait, ils ajouteront des instructions relatives à une plus grande compatibilité ou à l'inverse, ils retireront des portions inutilisées.

Quoiqu'il advienne, en complément des compresseurs ou non, votre code source d'origine reste intact.
Il est d'autant plus aisé de les tester, de les activer et de les désactiver quand bon vous semble.

*autoprefixer* ([URL]#https://npmjs.com/autoprefixer#) est _le_ module qui vous épargnera l'écriture de centaines de lignes en ajoutant automatiquement les bons préfixes aux bons endroits. 
Travail d'autant plus ingrat si vous n'avez pas envie ni le loisir de recourir à des _mixins_ Less ou Sass. +
_autoprefixer_ expose une API ECMAScript, un exécutable système ainsi qu'une API de _streaming_ permettant une intégration sans plugin avec *browserify*, entre autre.

.Exemple d'utilisation d'_autoprefixer_ en fonction des besoins en compatibilité navigateur
----
$ autoprefixer -o - src/snippets/sample.css | grep transition
  -webkit-transition: font-weight 0.2s ease;
          transition: font-weight 0.2s ease;
          
$ autoprefixer -b 'firefox > 8' -o - src/snippets/sample.css | grep transition
  -webkit-transition: font-weight 0.2s ease;
     -moz-transition: font-weight 0.2s ease;
          transition: font-weight 0.2s ease;
----

L'exemple précédent illustre comment la propriété `transition` a été préfixée pour couvrir les navigateurs ayant plus de 1% de part de marché, puis en incluant les versions supérieures à Firefox 8 — assez obsolètes il faut se l'avouer. +
Sans l'utilisation du paramètre `-o` (_output_), le fichier d'origine aurait été réécrit.

*uncss* ([URL]#https://npmjs.com/uncss#) est le pendant inverse d'_autoprefixer_ puisqu'il se charge de supprimer le code … mort.
Pour se faire, _uncss_ charge une ou plusieurs pages de référence et fait la différence entre les règles CSS utilisées … et celles qui ne le sont pas.
Libre à vous de mentionner une liste blanche de règles à ne jamais supprimer pour éviter qu'elles soient écrémées par mégarde.+
_uncss_ s'intègre particulièrement facilement dans les projet grâces à des plugins _grunt_ et _gulp_.

Si le monde de l'optimisation ECMAScript a explosé depuis l'apparition d'*esprima*, il en est de même pour CSS avec *PostCSS* ([URL]#https://npmjs.com/postcss#). +
Cet outil est construit autour du triptyque suivant :

- un parseur CSS ;
- un arbre syntaxique ;
- un compilateur texte.

Cette combinaison rend possible la production de _Source Maps_ mais aussi la construction d'une multitude d'outils destinés à faciliter la vie des développeurs.
Ces outils se greffent sur le parseur, l'arbre ou le compilateur pour parvenir à leurs fins. +
Avec une ou plusieurs extensions, vous avez ainsi accès à *autoprefixer*, à votre nettoyeur de code mort ou même à votre propre réimplémentation de Sass … entièrement en ECMAScript !

Enfin, il est bon de savoir que d'autres outils existent, complètent voire remplacent les compresseurs et optimiseurs précédemment cités :

- *Google Closure Compiler* ([URL]#https://npmjs.com/closurecompiler#) +
Un autre compilateur ECMAScript plus poussé qu'_UglifyJS_ mais imposant un style d'écriture plus strict, voire plus contraignant selon votre style d'écriture.
- *csswring* ([URL]#https://npmjs.com/csswring#) +
Une alternative plus moderne que _cssmin_.
Cet outil s'interface optionnellement avec _PostCSS_ et offre un support des _Source Maps_.
- *csso* ([URL]#https://npmjs.com/csso#) +
Une autre alternative à _cssmin_ et _csswring_ écrite par l'équipe derrière la méthodologie BEM ([URL]#https://en.bem.info#), moins bien documentée mais plus efficace en terme d'optimisations.
_csso_ ira jusqu'à réécrire les codes couleurs, les `margin` et `padding` et factorisera les sélecteurs similaires.

==== Optimisation des images

- génération de sprites
- réduction du poid des fichiers
- génération de vignettes
- SVG https://www.npmjs.com/svgo

==== Optimisation des fontes

- optimisation des chemins
- iconfontes
- https://npmjs.com/connect-fonts

==== Livereload

- watcher
- livereload

=== Automatisation des tâches avec Grunt

==== Configuration des tâches

==== Exécution des tâches

- par tâche
- par target
- tâches personnalisées
- arguments

==== Optimisation du temps de traitement

- grunt-newer
- grunt-lazyload

=== Vers un code isomorphique et modulaire

- approche simple d'objets partagés (inclusion, retour d'APIs)
- ECMAScript, CommonJS et AMD
- inclusion de bibliothèques fonctionnant côté Node et côté navigateur de manière transparente
- transformation du code avec un outillage spécifique

=== Transformation et empaquetage de code

==== browserify

==== Webpack

==== ender

=== Tester la compatibilité navigateur

==== Karma

==== SauceLabs

==== BrowserStack

==== Testling

==== Apium

=== Conclusion
