:nodeCurrentVersion: v6
:npmCurrentVersion: v4
:revdate: {docdate}
:sourceDir: ./examples
:imagesdir: {indir}
ifdef::env[]
:imagesdir: .
endif::[]

== [ChapitreNumero]#4# Développer pour les navigateurs web

La popularité de Node s'est établie également pour la profusion d'outillage apportée au développement web _frontend_.

Ce chapitre nous apprendra le rôle de Node en tant qu'extension au développement _frontend_.

====
.Sommaire
- Gérer les dépendances externes
- Créer des interfaces réactives
- Partager du code entre Node et le navigateur
- Automatiser des tâches pénibles et répétitives
- Automatiser les tests navigateurs
====

Avant l'apparition de Node, rare était l'outillage n'imposant pas une ou plusieurs plates-formes de développement : _YUICompressor_ demandait Java, _Google Closure Compiler_ demandait Java, _sprockets_ Ruby et _pngquant_ quelques dépendances système comme _libpng_.

Leur installation n'était pas triviale.
Leur coordination encore moins.
Les adapter aux différents systèmes d'exploitation et au système d'intégration continue n'était pas non plus aisé. +
Bref c'était lourd, complexe et compliqué à moins de disposer d'une infrastructure industrialisée.

L'existence de Node et du registre _npm_ a favorisé le développement d'un écosystème orienté _frontend_.
Cela s'étend de la découverte au téléchargement des bibliothèques tierces ainsi qu'à la compilation, l'optimisation et l'exécution des tests des applications web côté client.

[TIP]
.[RemarquePreTitre]#Remarque# Versions de Node et npm
====
Le contenu de ce chapitre se réfère aux versions de *Node {nodeCurrentVersion}* et *npm {npmCurrentVersion}*.
====

toc::[]

=== Éxécuter Node dans les navigateurs web ?

Ce chapitre peut sembler confus au premier abord.
Si Node s'exécute au niveau du système d'exploitation — "côté serveur" — en quoi est-il lié au développement _frontend_ — "côté client" ?
Est-ce parce que du code écrit pour Node peut aussi fonctionner dans un navigateur web ?
_Quid_ de l'utilisation de `require('fs')` pour accéder au système de fichiers ?

La réponse _courte_ est : *nous n'exécutons pas Node dans un navigateur web*.

Et la réponse _longue_ : *Node est utilisé pour assembler du code*, le _transformer_ et le rendre fonctionnel dans une paire de balises `<script></script>`. +
Ce code peut être aussi bien fourni par des *librairies tierces* installées via _npm_ (_jQuery_, _React_ ou _d3_ par exemple) que par de l'*outillage* (optimiseurs, suite de tests, orchestration de tâches etc.) ou encore par le *code réutilisable* de notre propre application web.

Il faut également bien comprendre qu'il y a plusieurs "problèmes" cachés sous une même question :

- Les navigateurs web et Node utilisent différentes machines virtuelles JavaScript, avec différents niveaux de complétion dans l'implémentation d'_ECMAScript_ ;
- Les navigateurs web et Node n'ont pas accès aux mêmes APIs – Node accède à `fs` et `http` tandis que les navigateurs ont `File` et `fetch`/`XmlHttpRequest` ;
- Les navigateurs web et Node ne gèrent pas le chargement de modules de la même manière – voir la section <<managing-dependencies,gestion des dépendances>> ;
- L'implémentation même d'_ECMAScript_ va différer selon les versions de Node employées – un navigateur moderne et Node 6 comprendraient l'objet natif `Promise` mais pas Node 0.12.

Ce processus n'est _pas magique_ et nous verrons graduellement au cours des prochaines sections comment tout ceci fonctionne.


=== Écrire dès à présent le code du futur

Transformer du code ECMAScript a pendant longtemps été chose pénible.
Je pense par exemple à de la minification de code (pour réduire les temps de transfert sur les antiques lignes ADSL 128K) ou à de la conversion automatique de code _ECMAScript 3_ en _ECMAScript 5_.
Cela nécessitait systématiquement l'utilisation d'un autre environnement qu'ECMAScript lui-même: Rhino nécessitait Java, Spidermonkey nécessitait C++ et Trident nécessitait un environnement Windows en plus de C++.

*esprima* chamboule les règles du jeu en décembre 2011 : ce parseur _ECMAScript_ — lui-même écrit en _ECMAScript_ – exporte une compréhension de code sous forme d'arbre syntaxique abstrait (_abstract syntax tree_, _AST_).
Cet arbre est lui-même analysable par de *nouveaux outils émergents* :

- les _source maps_ pour associer le code transformé au code d'origine, notamment dans les outils de développement des navigateurs web ;
- des _minifieurs_ plus efficaces et ayant connaissance des portions de code exécutées ;
- des _analyseurs de code_ pour informer le développeur d'erreurs de syntaxe, de non-respect de styles de développement etc. ;
- des _convertisseurs de code_ pour passer d'_ECMAScript_ vers _CoffeeScript_, de modules _CommonJS_ vers des modules _ECMAScript 2015_ etc.

[TIP]
.[RemarquePreTitre]#Lien# Annonce d'_esprima_
====
_Aryia Hidayat_ introduit exprima dans un billet de blog.
Il y présente notamment des comparatifs de performances d'exécution sur différentes VM ECMAScript et face à d'autres parseurs.

- [URL]#https://ariya.io/2011/12/introducing-esprima#
====

Le champ d'action de Node augmente, la versatilité d'_ECMAScript_ aussi. +
Toutefois si on ne devait retenir qu'une chose de tout ceci c'est qu'il est désormais normal d'*écrire du code moderne en anticipation des futurs standards et de le faire fonctionner sur les navigateurs actuels et anciens*.

==== La fin de l'approche par le dénominateur commun

TBD

[[transpilation]]
==== Écrire au plus proche des standards

TBD.


[TIP]
.[RemarquePreTitre]#Histoire# Traceur
====

_Traceur_ est un des premiers transpilateurs _ECMAScript 2015_ vers _ECMAScript 5_ à avoir émergé dans l'écosystème Node.

Il a permis de commencer à *écrire des modules en _ECMAScript 2015 bien avant que la spécification ne soit entièrement terminée*.
Et donc de pouvoir anticiper son apprentissage tout en mettant le langage à l'épreuve avant sa finalisation.
====

[[polyfills]]
==== Combler les manques avec des _polyfills_

TBD.


[[typescript]]
==== Écrire dans un autre langage : l'exemple TypeScript

TBD.

=== Une conception orientée composant

TBD.

==== Le syndrôme du plugin jQuery

TBD.

==== Vers une approche jQuery composite

TBD.

==== Partager le code métier avec Node

TBD.

==== Séparation du fond et de la forme : données, rendu et interactions

TBD.

==== Rapprocher présentation et interactions avec React

TBD.

==== Lier composants et feuilles de style

TBD.

[[io]]
=== Des requêtes AJAX au temps-réel

TBD.

[[io-fetch]]
==== Consommer des données hétérogènes avec `fetch()`

TBD.

[[io-sse]]
==== Approche unidirectionnelle avec _Server Sent Events_

TBD.

[[io-websockets]]
==== Échanges en temps-réel avec _Websockets_

TBD.


=== Tester son code


==== Écrire des tests avec tape et chai

TBD.

==== Exécuter les suites de tests avec Karma

TBD.

==== Tester les éléments de lisibilité et de performance

TBD.

==== Tester la compatibilité navigateurs avec BrowserStack

TBD.

==== Le cas Internet Explorer et ievms

TBD.

=== Conclusion

TBD.
