== [chapterNumber]#1# Introduction à Node.js

[.lead]
Node.js génère beaucoup de discussions, d'intérêts et d'envies. +
Dans ce chapitre, nous allons faire le point sur ce qu'est Node.js pour mieux comprendre dans quel cambouis nous allons plonger les mains.

====
.Sommaire
- Comprendre ce qu'est Node.js
- Savoir qui gère Node.js au quotidien
- Décider si Node.js peut compléter ou remplacer un système en place
- Pourquoi autant de _hype_ ?
====

Node.js est-il un langage de programmation ? Node.js est-il un _framework_ JavaScript ? Qu'en restera-t'il une fois que la frénésie retombera ?

Ce chapitre n'est pas essentiel à l'apprentissage de Node.js. Il permet de comprendre pourquoi et comment Node a émergé. Surtout, il vous permettra de comprendre des choix techniques à l'origine de ses fondations, et en quoi l'utiliser peut vous apporter en contexte personnel ou professionnel.

Mais qu'on se le dise : un langage de programmation en lui-même n'a jamais solutionné quelconque problème. Cela reste avant tout une affaire de compétences et d'expérience.


=== Node.js : la plateforme JavaScript côté serveur

=== Historique du projet Node.js

=== Les raisons du succès

=== Pourquoi choisir Node.js ?

=== Pourquoi éviter Node.js ?

=== L'écosystème Node.js

==== Joyent

==== Nodejitsu

==== Node Security Project

=== Qui gère Node.js ?