== [titre-nombre]#Annexe X# Contributions sociales

[.lead]
Je me suis souvent servi de Twitter comme moyen de sondage rapide lors de l'écriture du livre.

Cette annexe reprend les différentes questions et réponses échangées.

>>>

Certaines ont apporté de nouveaux éléments tandis que d'autres ont infirmé ou confirmé mes hypothèses.

- réagir aux précédentes conversations
- crédit

=== Quelles sont les grosses entreprises françaises qui utilisent Node.js ?

> https://twitter.com/oncletom/status/444882574322966528

https://twitter.com/tiboll/status/444883182153138176

https://twitter.com/zeroload/status/444884960839999488

https://twitter.com/franckverrot/status/444886814441349120

https://twitter.com/j0k/status/444894339735748609

https://twitter.com/nhoizey/status/444907515114164224

=== Quelles sont les raisons pour lesquelles vous n'utiliseriez pas Node.js ?

> https://twitter.com/oncletom/status/445287024984338432


https://twitter.com/matti_sg/status/445287019749851136

https://twitter.com/fcamblor/status/445287901342236672

https://twitter.com/dascritch/status/445288603191869440

https://twitter.com/euskadi31/status/445295029851271169

https://twitter.com/SamyRabih/status/445310758302519297

https://twitter.com/JulienITARD/status/445313602351005697

https://twitter.com/toutpt/status/445495918109134848

https://twitter.com/antoinelyset/status/445507321956159488

https://twitter.com/antoinelyset/status/445507741936021504

https://twitter.com/goldoraf/status/445529411220418561

https://twitter.com/_kud/status/445531049301651456

https://larlet.fr/david/blog/2014/utiliser-nodejs/

https://twitter.com/GregorySalvan/status/445958649962565632

https://twitter.com/pierremartin/status/446027625329602560

https://twitter.com/edas_public/status/446029052739342338
https://twitter.com/edas_public/status/446029103125516288
https://twitter.com/edas_public/status/446029153457160193
https://twitter.com/edas_public/status/446029216875053056

=== Modules essentiels

> https://twitter.com/oncletom/status/447432700463677441

https://twitter.com/ArnaudRinquin/status/447433247765843968
https://twitter.com/ArnaudRinquin/status/447435123647328258

https://twitter.com/FGRibreau/status/447433330527838208

https://twitter.com/pgte/status/447436219535093761

https://twitter.com/krachot/status/447449557946085377

https://twitter.com/goldoraf/status/447452882565341184

https://twitter.com/jonathanperret/status/447478654223003648


=== Snippets

==== Exposer un composant web avec Node

Il peut arriver que vous ayiez besoin de servir certaines ressources de modules via HTTP sans utiliser de préprocesseur ou d'outil de compilation.

Le _framework_ _express_ ([URL]#https://expressjs.com/#) met à disposition un mécanisme de _montage d'URL_.
En combinant ce mécanisme avec la méthode `express.static`, il devient alors possible d'exposer n'importe quel fichier inclut dans _npm_modules_ (ou autre répertoire) en tant que ressource web.

[source,javascript]
.npm-express.js
----
include::{sourceDir}/npm-express.js[]
----
<1> Rend accessible le fichier `jquery.js` à l'adresse `http://localhost:3000/assets/jquery.js` ;
<2> Rend accessible le répertoire `node_modules` à l'adresse `http://localhost:3000/assets` et donc d'une autre manière, le fichier `jquery.js` à l'adresse `http://localhost:3000/assets/jquery/dist/jquery.js`.
