== Préface

Here. put that in your report!" and "i may have found a way out of here. what you have to ask yourself is, do i feel lucky. well do ya' punk? don't p!ss down my back and tell me it's raining. you see, in this world there's two kinds of people, my friend: those with loaded guns and those who dig. you dig. are you feeling lucky punk you want a guarantee, buy a toaster. ever notice how sometimes you come across somebody you shouldn't have f*ked with? well, i'm that guy. you want a guarantee, buy a toaster. this is the ak-47 assault rifle, the preferred weapon of your enemy; and it makes a distinctive sound when fired at you, so remember it. dyin' ain't much of a livin', boy. here. put that in your report!" and "i may have found a way out of here. dyin' ain't much of a livin', boy.

Are you feeling lucky punk you want a guarantee, buy a toaster. man's gotta know his limitations. don't p!ss down my back and tell me it's raining. this is my gun, clyde! don't p!ss down my back and tell me it's raining. well, do you have anything to say for yourself? man's gotta know his limitations. this is the ak-47 assault rifle, the preferred weapon of your enemy; and it makes a distinctive sound when fired at you, so remember it. well, do you have anything to say for yourself? don't p!ss down my back and tell me it's raining. what you have to ask yourself is, do i feel lucky. well do ya' punk?

This is my gun, clyde! well, do you have anything to say for yourself? ever notice how sometimes you come across somebody you shouldn't have f*ked with? well, i'm that guy. dyin' ain't much of a livin', boy. you want a guarantee, buy a toaster. dyin' ain't much of a livin', boy. are you feeling lucky punk when a naked man's chasing a woman through an alley with a butcher knife and a hard-on, i figure he's not out collecting for the red cross. what you have to ask yourself is, do i feel lucky. well do ya' punk? man's gotta know his limitations. ever notice how sometimes you come across somebody you shouldn't have f*ked with? well, i'm that guy. what you have to ask yourself is, do i feel lucky. well do ya' punk?

You see, in this world there's two kinds of people, my friend: those with loaded guns and those who dig. you dig. are you feeling lucky punk here. put that in your report!" and "i may have found a way out of here. this is the ak-47 assault rifle, the preferred weapon of your enemy; and it makes a distinctive sound when fired at you, so remember it. when a naked man's chasing a woman through an alley with a butcher knife and a hard-on, i figure he's not out collecting for the red cross. you see, in this world there's two kinds of people, my friend: those with loaded guns and those who dig. you dig. well, do you have anything to say for yourself? man's gotta know his limitations. this is my gun, clyde! when a naked man's chasing a woman through an alley with a butcher knife and a hard-on, i figure he's not out collecting for the red cross. here. put that in your report!" and "i may have found a way out of here. this is the ak-47 assault rifle, the preferred weapon of your enemy; and it makes a distinctive sound when fired at you, so remember it.
