:nodeVersion: v0.10
:nodeNextVersion: v0.12
:es: ECMAScript 5
:esNext: ECMAScript 6
:sourceDir: ../../examples/nodebook.chapter-03/src
:revisionYear: 2014

== [ChapitreNumero]#3# Mon premier projet Node.js

Maintenant que nous en savons davantage sur Node en théorie et en pratique, il est temps de plonger dans un vrai projet : plusieurs fichiers, plusieurs dépendances et des tests.

Ce chapitre se focalise sur la conception d'une application système modulaire et robuste.
Nous apprendrons à réaliser nos premiers tests unitaires et à laisser la porte ouverte à l'intégration de cette application avec d'autres programmes.

====
.Sommaire
- Initialiser un projet
- Choisir, installer et gérer des dépendances
- Organiser son code de manière modulaire
- Tester son code
- Design patterns
====

Node excelle dans l'accès aux données et à leur redistribution.
À ce titre, nous allons développer une application qui permet de collecter les données du budget de la ville de Bordeaux.
Ces données sont mises à disposition sous licence libre au format Excel sur le portail Open Data de la ville [URL]#http://opendata.bordeaux.fr/#.

Une fois les données récupérées, nous voudrions éviter de nous retrouver coincé : nous allons permettre la distribution des données vers un autre programme mais aussi vers une API HTTP qui pourrait stocker les données pour une utilisation ultérieure.

Cet exemple d'application vous permettra de couvrir l'essentiel de ce qu'il faut savoir pour créer une application système sans pour autant se fermer les portes.

=== Initialisation du projet

Que notre idée tienne en un fichier ou en plusieurs, tout projet Node dispose de son rituel : la création du fichier `package.json`.

==== package.json

Le fichier `package.json` est un élément incontournable de tout projet Node.
Il contient plusieurs niveaux d'informations :

- *textuels* : titre, descriptions, liens et licence ;
- *version* : une chaîne respectant le fonctionnement de _node-semver_ ([URL]#https://github.com/isaacs/node-semver#) ;
- *dépendances* : emplacement du module principal et liste explicite de modules nécessaires au bon fonctionnement du projet ;
- *actions* : commandes à exécuter automatiquement ou manuellement ;
- *divers* : données de configuration ou utilisées par des modules Node.

[TIP]
.[RemarquePreTitre]#Commande# npm help json
====

====

==== npm init

[source]
----
npm init
----

==== Organiser son espace de travail

==== Intégration avec Git

=== Tester le code

==== Qualité syntaxique

==== Tests unitaires

=== Design patterns

==== Modules

==== Injection

==== Callbacks

==== Évènements

==== Promesses

==== Héritage prototypal

==== Application partielle

=== Choisir ses modules npm

==== Modules populaires

