[dedication]
= Avant-propos

*Node.js* – appelons-le *Node* dès à présent – est né dans le cerveau de Ryan Dahl, ancien étudiant sans le sou et au parcours informatique atypique.
Son talent a été de s'obstiner à *résoudre un problème d'expérience utilisateur* fréquent sur le web : *l'attente devant un navigateur web figé*.
Son but ? Rendre possible et facile la création de *barres de progression* dans les navigateurs Web.

J'ai utilisé Node pour la première fois en 2010, par curiosité.
On en était alors qu'à la version `0.4`.
Pouvoir créer mon propre serveur HTTP me semblait étrange, moi qui était un habitué du duo PHP et Apache.
*L'effet _wahou_ était pourtant là* : une installation en quelques secondes, quelques lignes de JavaScript et j'avais une API REST câblée avec une base de données _CouchDB_ pour impressionner mes collègues de l'agence _Clever Age_.

Je bascule dans un *contexte startup* fin 2011 : nous sommes quatre développeurs avec des bagages différents.
Nous partons sur Node que notre hébergeur _Alwaysdata_ installe sans encombre.
Nous avions la *sensation de progresser rapidement*.
Nous allions _réellement_ vite. +
*JavaScript était devenu notre langue commune grâce à Node*.

Depuis, de nombreuses entreprises ont communiqué sur leur adoption de Node :  Paypal, LinkedIn, eBay, Airbnb, British Gaz, Allociné, The New York Times, Yahoo!, Microsoft, Mozilla, Flickr ou encore Twitter.
Leur utilisation couvre aussi bien l'outillage métier que les transactions bancaires, des serveurs LDAP, des web services ou des sites web.

Pourtant, nombre d'ouvrages et de ressources se focalisent uniquement sur le dernier _framework_ ou librairie à la mode en passant à côté de l'essentiel.

== Pourquoi ce livre ?

*Node est un environnement plaisant et agréable à utiliser*, c'est ce que j'aime et aspire à partager avec vous au cours des prochaines pages de cet ouvrage.

Node est *mon outil de travail principal* depuis 2011.
Outillage, tests, API, applications, prototypes et automatisation.
Sa simplicité, son architecture et l'emphase sur la modularité m'ont fait *progresser dans l'usage de JavaScript* ainsi que sur la compréhension bas-niveau des systèmes d'exploitation.

Je souhaite offrir un *contenu moins technique que d'ordinaire*, plus pratique et encourageant la bidouille : le livre lui-même peut être installé avec Node, lu et pratiqué dans un _shell_.

Je souhaite aussi *partager les principes clés de Node* et de la programmation JavaScript.
Ces principes traversent le temps et vous donnerons, je l'espère, un appétit et des bases plus solides pour créer de petits programmes, faire un prototype rapide ou déployer une application complète.

Enfin, l'écriture de ce livre est également pour moi l'occasion d'*apprendre de mes pairs*, de leurs heures d'expérience en tant que formateurs, d'explorer des sujets qui me font peur et sur lesquels je ne me sens pas à l'aise.

Indirectement, je veux *déconstruire la posture de l'expert et du lecteur* en ouvrant le contenu pendant le processus d'écriture, dans un endroit où éditeur, lecteurs et auteurs apprennent les uns des autres.

== À qui s'adresse cet ouvrage ?

Réponse _courte_ : *à tout le monde*. Vraiment.

Réponse _informelle_ : à toute *personne curieuse* ou *souhaitant apprendre* ou *s'améliorer en programmation*, sans forcément trop savoir par où commencer.
Je crois fermement qu'apprendre à programmer n'implique pas de faire de la programmation son métier ni de pratiquer sans erreur – on peut avoir envie de *découvrir par plaisir*, par *envie de comprendre* ses pairs ou pour *engager une conversation* avec ses collègues.

Réponse _formelle_ :

* à des personnes dont la *programmation est le métier* mais pratiquant peu ou pas assez JavaScript ;
* à des personnes adeptes du *développement _frontend_* et cherchant à mieux s'outiller ;
* à des *personnes non-techniques* qui chercheraient à prototyper une idée d'application dans le cadre d'un projet perso ou d'une startup ;
* à des personnes souhaitant *introduire de nouvelles pratiques* dans leur équipe ;
* à des personnes cherchant à faire de JavaScript une *langue commune entre le _backend_ et le _frontend_* de leurs applications.

== Structure de l'ouvrage

Cet ouvrage a été conçu pour être lu dans _deux ordres_ : *séquentiel*, comme une histoire et *transversal*, en fonction de vos envies.

Cette édition se compose de _six chapitres_ :

. *Introduction à Node.js* +
  Comprendre d'où vient Node, les acteurs de son histoire, ses relations avec JavaScript, son architecture technique ainsi que sa philosophie de développement.
. *Premiers pas avec Node.js* +
  Installer Node sur son ordinateur, quels outils choisir pour développer, découvrir les concepts UNIX dont Node hérite, comment créer et gérer un projet Node, (re)découvrir les primitives et motifs de conception JavaScript… mais au fait, c'est quoi _ECMAScript_ ?
. *Développer une application web* +
  Comprendre le modèle de serveur de Node, comment créer une application web et une API RESTful, la connecter avec plusieurs types de base de données, la tester unitairement et fonctionnellement tout en découvrant comment partager des blocs de présentation entre serveur et client.
. *Développer pour les navigateurs web* +
  Peut-on exécuter Node ou importer des modules _npm_ dans les navigateurs web ? Découvrir comment écrire du code au plus proche des standards — JavaScript et CSS mais aussi comment s'outiller pour éliminer les tâches répétitives tout en augmentant qualité de vie et qualité de code.
. *Développer un automate de traitement de données* +
  Comment manipuler un fichier dont la taille est plus importante que la quantité de mémoire disponible ? Apprendre à appliquer des transformations successives sans accéder au disque grâce au _streaming_ de données.
. *Héberger, déployer et monitorer* +
  Quel type d'hébergement choisir, comment déployer ses applications, s'assurer de leur fonctionnement et de leur santé sans compromettre leur sécurité.

Une *annexe* présente une sélection de modules _npm_ pour explorer d'autres horizons – énième démonstration de la versatilité de Node.

Cet ouvrage est également consultable sur _quatre supports_ :

- *livre*, idéal pour les annotations ;
- *e-book*, idéal pour consommer les batteries de votre liseuse numérique ;
- *web*, idéal pour bénéficier des contenus multimédia, des ajouts récents et des corrections diverses;
- *npm*, idéal pour exécuter les exemples dans votre terminal et apprendre en bidouillant.

[TIP]
.[RemarquePreTitre]#Ressources# Contenu en [line-through]#livre# libre accès
====
Le contenu de cet ouvrage est géré grâce à la plate-forme collaborative _GitHub_.
Cette plate-forme me permet d'obtenir des retours, idées et suggestions d'un peu tout le monde… peut-être vous ?

- [URL]#https://github.com/oncletom/nodebook#
- [URL]#https://npmjs.com/nodebook#
====

== Remerciements

Cet ouvrage a été rédigé sur près de _trois années_ – longue est la liste exhaustive des personnes à remercier.
Longue aussi est la liste de celles et ceux à qui je dois m'excuser pour mes sautes d'humeur, mes absences ou mes passages à vide.
Écrire est une activité éprouvante qui nécessite une attention vis à vis de soi-même pour ne pas (trop) en souffrir.

Mes premiers remerciements vont à _Eyrolles_, mon éditeur.
Je pense à Karine, Laurène et Elsa mais aussi à Alexandre pour leur patience infinie, leurs remarques et leur confiance malgré tous ces rebondissements.

Je te remercie tellement Noémie.
Ta joie, tes encouragements et ta présence sont essentiels à mon équilibre.
Ils me donnent confiance, m'inspirent et atténuent les peurs qui peuvent me paralyser.

Je me dois aussi de remercier mes anciens collègues de BBC R&D pour leur soutien, leur confiance et leur tolérance aux jeux de mots.
Olivier, Sean, Katie, Chris N et Chris L… c'était un plaisir et un honneur d'être à vos côtés.

Certain·e·s d'entre vous m'ont beaucoup aidé de par leurs conseils, leurs relectures et leurs encouragements.
Alors un grand merci Frank, Thierry, Boris, Béa, Efi, Alexandra, Thomas, Xavier, Bastien, Nicolas C, n1k0 et Loic.

J'ai organisé une résidence d'écriture itinérante de janvier à mars 2017.
On m'a hébergé, nourri et parfois blanchi.
Merci beaucoup beaucoup Maxime W, Brice F, Nicolas F, les gens du Yelloworking à Aix, Antoine F, les gens de la Coop à Grenoble, Cédric et Hélyette, Agnès, les gens de Mix-IT, les gens de la Cordée à Lyon, Maxime L, les gens de la Myne à Villeurbane, Clément D et Quentin A, les gens de Clever Cloud, Thomas M et Lilian M, les gens du ByteClub, Alexis J, les gens de Matlo, les gens du Fab Lab 127°, Arnaud R, Ismaël H et les gens de BetaGouv.

Enfin, entre meta-remerciements et méga-encouragements, je suis heureux et fier d'œuvrer d'ensemble, avec David et Clémentine, afin de porter nos valeurs et nos idées vers les Communs et la mutualisation de moyens.

Mes amis. Ma famille. Je vous aime.

Bonne lecture icon:smile-o[]

— Thomas Parisot
[URL]#https://oncletom.io#
